package edu.phoenixforce.scouting.mobile.database.The_other_ways_of_scoring;

public class scores {
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
    //merge error
}
